version: "3.5"
services:
  arm_control:
    image: dimitrivinet/alfred:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: "/bin/bash"
    ports:
      - "8080:8080"
    environment:
      - ARM_IP=10.1.30.250
    depends_on: 
      - rasa
    networks:
      - alfred
  rasa:
    image: dimitrivinet/rasa-api:latest
    ports:
      - "5005:5005"
    networks:
      - alfred

networks:
  alfred: